const C = {
  SUBMIT_ANSWER: "SUBMIT_ANSWER",
  ON_ANSWER_CHANGE: "ON_ANSWER_CHANGE",
  SET_CURRENT_QUESTION: "SET_CURRENT_QUESTION",
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT"
};

export default C;
